version: '3'

networks:
  api:

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:10.10-alpine
    container_name: postgres
    restart: unless-stopped
    tty: true
    ports:
      - '8080:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: blog
      POSTGRES_SCHEMA: core
    volumes:
      - ./docker/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/database:/var/lib/postgresql/data
    networks:
      - api

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@localhost.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - postgres
    networks:
      - api
